#! /usr/bin/env bash
#~----------------------------------------------------------------------------~#
# placeholder
#~----------------------------------------------------------------------------~#
#
#------------------------------------------------------------------------------#
# Choose support for HDF5 output for fields and hydro
#------------------------------------------------------------------------------#
# One of the two available options must be chosen. Valid options are ON and
# OFF.
#
# If SET_HDF5=OFF, the output of fields and hydro are in binary format.
#
# If SET_HDF5=ON, the output of fields and hydro are in HDF5 format.
#------------------------------------------------------------------------------#
SET_HDF5="OFF"
# SET_HDF5="ON"

#------------------------------------------------------------------------------#
# Get the path to the project from which this script was called
#------------------------------------------------------------------------------#

src_dir="${0%/*}/.."

#------------------------------------------------------------------------------#
# Check required environment variables
#------------------------------------------------------------------------------#

# module load PrgEnv-gnu
module load cmake
module load craype-accel-amd-gfx90a
module load rocm
module load cce
module load kokkos/4.3.00-gpu

export MPICH_GPU_SUPPORT_ENABLED=1

# compiler environment hints
export CC=$(which hipcc)
export CXX=$(which hipcc)
export HIPFLAGS="--offload-arch=gfx90a"
# export CFLAGS="-I${ROCM_PATH}/include -I${MPICH_DIR}/include"
# export CXXFLAGS="-I${ROCM_PATH}/include -I${MPICH_DIR}/include -Wno-pass-failed"
# export LDFLAGS="-L${ROCM_PATH}/lib -lamdhip64 -L${MPICH_DIR}/lib -lmpi ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}"
export CFLAGS="-I${MPICH_DIR}/include ${HIPFLAGS}"
export CXXFLAGS="-I${MPICH_DIR}/include -Wno-pass-failed ${HIPFLAGS}"
export LDFLAGS="-L${MPICH_DIR}/lib -lmpi ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}"
# export CC=cc
# export CXX=CC
# export CFLAGS="-std=c++11 -D__HIP_ROCclr__ -D__HIP_ARCH_GFX90A__=1 --rocm-path=${ROCM_PATH} --offload-arch=gfx90a -x hip"
# # export CXXFLAGS="-I${ROCM_PATH}/include -Wno-pass-failed"
# export LFLAGS="-rocm-path=${ROCM_PATH} -L${ROCM_PATH}/lib -lamdhip64"

if [ "$SET_HDF5" = "ON" ]
then
    module load cray-hdf5-parallel
fi
module list 2>&1 | tee modules.txt

#------------------------------------------------------------------------------#
# Call CMake command
#------------------------------------------------------------------------------#

# The flag -rdynamic removes warnings of the form:
# Unable to find a safely writable symbol that corresponds to address 432af0
# (the closest match was "(null)" from "./lpi_2d_F6_test.Linux").  Writing out
# the raw address instead and keeping my fingers crossed.

# In the Cray environment, there is a bit of confusion about compilers and
# wrappers and such.  I've worked around it with some ad hoc CMake magic, but
# this line might be helpful when troubleshooting (run it when compiling user
# decks too).
# export NVCC_WRAPPER_DEFAULT_COMPILER=$(which CC)
  # -DCMAKE_CXX_COMPILER="CC" \

CRAYPE_LINK_TYPE=dynamic cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DENABLE_INTEGRATED_TESTS=ON \
  -DENABLE_UNIT_TESTS=ON \
  -DBUILD_INTERNAL_KOKKOS=OFF \
  -DKokkos_ENABLE_TUNING=ON \
  -DKokkos_ENABLE_OPENMP=ON \
  -DKokkos_ENABLE_HIP=ON \
  -DKokkos_ARCH_GFX90A=ON \
  -DKokkos_ARCH_ZEN3=ON \
  -DROCM_ROOT=${ROCM_PATH} \
  -DCMAKE_CXX_FLAGS="-g -dynamic ${CXXFLAGS}" \
  -DVPIC_CXX_LIBRARIES="${LDFLAGS}" \
  -DVPIC_ENABLE_HDF5=$SET_HDF5 \
  $src_dir

  # -DKokkos_ENABLE_SERIAL=ON \
  # -DKokkos_ARCH_NATIVE=ON \
  # -DKokkos_ENABLE_COMPILER_WARNINGS=ON \
  # -DKokkos_ENABLE_DEPRECATED_CODE_4=ON \
  # -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF \
  # -DAPEX_WITH_HIP=TRUE \
  # -DKokkos_ENABLE_AGGRESSIVE_VECTORIZATION=ON \
#------------------------------------------------------------------------------#
# Choose number of parallel make processes for build.
#------------------------------------------------------------------------------#
# If NJ variable is not defined, "make" will perform a parallel build using
# maximum number of processors on the compilation machine.
#
# If using VERBOSE = 1 and NJ > 1, verbose output will be garbled by many
# processes writing to STDOUT at the same time and will be difficult to
# interpret.
#
# When using VERBOSE = 1,  use of NJ = 1 is recommended.
#
# The default is to use a modest number of processes in the parallel build.
#
# Comment out default below to use all processors on compilation machine.
#------------------------------------------------------------------------------#

#NJ=8
NJ=4

#------------------------------------------------------------------------------#
# Choose verbosity of "make" output.
#------------------------------------------------------------------------------#
# Setting VERBOSE = 1 causes "make" to output commands it is executing.
#
# This information is useful if debugging a failed build.
#
# Setting VERBOSE = 0 or leaving VERBOSE undefined results in a quiet build.
#
# The default is a quiet build.
#------------------------------------------------------------------------------#

#SET_VERBOSE=0
SET_VERBOSE=8

#------------------------------------------------------------------------------#
# Call make command.
#------------------------------------------------------------------------------#
# Notes:
#
# In general, it is necessary to call the "make" command within this script
# because the module environment has been configured within this script.
#
# Setting VERBOSE=1 causes "make" to output the commands it is executing.
# This information is useful if debugging a failed build.
#
# If the NJ variable is not defined, "make" will perform a parallel build
# using maximum number of processors on the compilation machine. If using
# VERBOSE=1, the verbose output will be garbled by many processes writing
# to STDOUT at the same time and will be difficult to interpret. When using
# VERBOSE=1, it can be helpful to also use NJ=1.
#------------------------------------------------------------------------------#

make -j $NJ VERBOSE=$SET_VERBOSE

#------------------------------------------------------------------------------#
# Done.
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# vim: syntax=sh
#------------------------------------------------------------------------------#
