name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install deps
      run: sudo apt-get update; sudo apt-get install gfortran openmpi-bin libopenmpi-dev libhdf5-openmpi-dev
    - name: Checkout vpic and kokkos
      uses: actions/checkout@v2
      with:
        submodules: recursive
        #repository: kokkos/kokkos
        #ref: 3.1.00
        #path: kokkos
    - name: Build kokkos
      working-directory: kokkos
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX=$HOME/kokkos -DCMAKE_CXX_STANDARD=17
        cmake --build build --parallel 2
        cmake --install build
    #- uses: actions/checkout@v2
    - name: configure with external
      run: cmake -B build -DCMAKE_PREFIX_PATH="$HOME/kokkos" -DENABLE_UNIT_TESTS=ON -DENABLE_INTEGRATED_TESTS=ON -DVPIC_ENABLE_HDF5=ON -DCMAKE_CXX_FLAGS="-rdynamic -fno-strict-aliasing"
    - name: make external
      run: cmake --build build
    - name: make check
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13' 
            cache: 'pip'
        - run: pip install numpy h5py
      run: ctest --output-on-failure
      working-directory: build
    - name: configure with internal
      run: cmake -B build_internal -DBUILD_INTERNAL_KOKKOS=ON -DENABLE_UNIT_TESTS=ON -DENABLE_INTEGRATED_TESTS=ON -DVPIC_ENABLE_HDF5=ON -DCMAKE_CXX_FLAGS="-rdynamic -fno-strict-aliasing"
    - name: make internal
      run: cmake --build build_internal
